#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

if [[ -d "${ZDOTDIR:-$HOME}/.zsh.d" ]]; then
  for f in ${ZDOTDIR:-$HOME}/.zsh.d/*rc; do
    [ -e "$f" ] && source $f || echo "$f do not exist"
  done
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/hiroseyuudai/google-cloud-sdk/path.zsh.inc' ]; then source '/Users/hiroseyuudai/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/hiroseyuudai/google-cloud-sdk/completion.zsh.inc' ]; then source '/Users/hiroseyuudai/google-cloud-sdk/completion.zsh.inc'; fi

